PROJECT: ASSOCIATIONS - Private Events
SafaErden/Private-Events pull request #1
Opened 2020-06-30 13:05 UTC by SafaErden

In this project, we built a site which allows users to create events and manage user signups 

We built models with associations, views, controllers for;
- Sign Up and Sign In page,
- Invitation,
- Event Attendance interactions.

Additionally, we used Bootstrap to build UI.

We created test files with Rspec and Capybara.

2020-06-30 18:02 UTC, wathigo requested changes
### Changes Required.
Great work team!
Let's fix some issues before moving on.

**REQUIRED**
* Navigation links are present at the top of the page ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from Odin). Currently, it's impossible to logout after a successful login. Let's add a log out link on the navigation bar.
* It's impossible to create a user from the views but everything works well on the console. Let's debug this.
* See the comments for more suggestions :point_down: 

**After working on the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

2020-06-30 18:02 UTC, wathigo commented on app/controllers/users_controller.rb
> +    @events = @current_user.events
**REQUIRED**
* Lists events previoulsy attendented by user using event model scope([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from Odin).
This can be implemented as follows.
```ruby
@attended_past_events = current_user.attended_events.previous_events
```
The same case applies for attended future events.

2020-07-01 10:40 UTC, stratospherique requested changes
### Great Progress @team :clap: :clap: However, some requirements weren't implemented. Check :arrow_down: 

- **[REQUIRED]** Signup using the views is still impossible. Kindly fix :gear: 
  - authenticate_user method is probably blocking the signup process.
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-07-01 17:39 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap:
### There is one failed test, lets fix it
#### You can go ahead and merge once done !!!

2020-07-02 08:13 UTC, merged

2020-07-02 08:19 UTC, krys2fa commented
Thanks @kobiyoyo.